spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    show-sql: false
  output:
    ansi:
      enabled: always

auth:
  jwt:
    secret: ${SECRET_KEY:wanseoSecret}

server:
  port: 8000
  address: 0.0.0.0

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET_NAME}
    region:
      static: ${S3_REGION}
    stack:
      auto: fasle