name: CICD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      S3_REGION: ${{ secrets.S3_REGION }}

    steps:
      - uses: actions/checkout@v2

      - name: use JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: grant privileges to gradlew
        run: chmod +x gradlew

      - name: run test
        run: ./gradlew test

      - name: run build
        run: ./gradlew clean build -x test

  CD:
    runs-on: ubuntu-latest
    needs: CI

    steps:
      - uses: actions/checkout@v2

      - name: use JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: grant privileges to gradlew
        run: chmod +x gradlew

      - name: run build
        run: ./gradlew clean build -x test

      - name: create docker image
        run: docker build --tag shaworld-backend .

      - name: upload to docker hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sonwanseo/shaworld-backend
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}